const placesclavero = [
    {
        id: 1,
        name: "Altas Cumbres y Pampa de Achala - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 2,
        name: "Puentes Colgantes - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 3,
        name: "Balneario Nido de Aguilas - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 4,
        name: "Balneario La Toma - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 5,
        name: "Balneario Los Elefantes - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 6,
        name: "Nacimiento del Río Mina Clavero - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 7,
        name: "Playa del rio de los Sauces - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 8,
        name: "Balneario la Residencia - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 9,
        name: "Playas del centro - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
    {
        id: 10,
        name: "Balneario Abuela Teresa - Mina Clavero",
        desp: "La actual plaza fue remodelada en los años 1987-1991 por el arquitecto Julio Lemoine. Según el trazado colonial, todo el pueblo se organizó alrededor de una plaza, cuando se fundó La Paz se delimitó la plaza y calles aledañas. Antiguamente la plaza estaba rodeada de alambre para que los animales no entraran. En el centro de ésta había un pozo balde de donde los habitantes sacaban el agua para el consumo.",
        img_1: "../imgs/turisticos/la-paz/1/juegos-plaza-la-paz.jpg",
        img_2: "../imgs/turisticos/la-paz/1/juegos-plaza-1-la-paz.jpg",
        img_3: "../imgs/turisticos/la-paz/1/iglesia-y-plaza-la-paz.jpg",
        location: "https://www.google.com/maps/place/32%C2%B013'02.8%22S+65%C2%B002'54.2%22W/@-32.217441,-65.048378,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-32.217441!4d-65.048378?entry=ttu&g_ep=EgoyMDI1MDQxMy4wIKXMDSoJLDEwMjExNjM5SAFQAw%3D%3D",
    },
];

export default placesclavero;